### ISSUE TITLE
Cannot open include file: 'boost/multiprecision/cpp_int.hpp'

### ISSUE THREAD

**Issue by TechyGuy17** [weniseb/RSA_CPP#2]
Hello, i have been trying to implement this system in to a project of mine but the compiling always fails at the same place, 
Cannot open include file: 'boost/multiprecision/cpp_int.hpp'

I have been trying to move around both the boost directory and the include statement but without success, is there anyone that can help me?

**Comment by AlexFalzone** [comment]
@TechyGuy17 From what I can see boost is inside lib. Have you tried editing includes?

**Comment by TechyGuy17** [comment]
Hello! Thank you for response, but I gave up on this long time ago and just forgot to close the issue
